// Code generated by structify-go; DO NOT EDIT.

package main

type UserResponse struct {
	Active   bool        `json:"active"`
	Age      int         `json:"age"`
	Metadata interface{} `json:"metadata"`
	Profile  Profile     `json:"profile"`
	Projects []Project   `json:"projects"`
	Roles    []string    `json:"roles"`
}

type Profile struct {
	Email string  `json:"email"`
	Score float64 `json:"score"`
}

type Project struct {
	ID   int      `json:"id"`
	Name string   `json:"name"`
	Tags []string `json:"tags"`
}
