package naming

import (
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

var commonInitialisms = map[string]string{
	"api":   "API",
	"ascii": "ASCII",
	"cpu":   "CPU",
	"css":   "CSS",
	"dns":   "DNS",
	"eof":   "EOF",
	"fa":    "FA",
	"guid":  "GUID",
	"html":  "HTML",
	"http":  "HTTP",
	"https": "HTTPS",
	"id":    "ID",
	"ip":    "IP",
	"json":  "JSON",
	"lhs":   "LHS",
	"qps":   "QPS",
	"ram":   "RAM",
	"rhs":   "RHS",
	"rpc":   "RPC",
	"sla":   "SLA",
	"smtp":  "SMTP",
	"sql":   "SQL",
	"ssh":   "SSH",
	"tcp":   "TCP",
	"tls":   "TLS",
	"ttl":   "TTL",
	"udp":   "UDP",
	"ui":    "UI",
	"uid":   "UID",
	"uuid":  "UUID",
	"uri":   "URI",
	"url":   "URL",
	"utf8":  "UTF8",
	"vm":    "VM",
	"xml":   "XML",
	"xsrf":  "XSRF",
	"xss":   "XSS",
}

func ToFieldName(input string) string {
	return toExportedName(input, "Field")
}

func ToTypeName(input string) string {
	return toExportedName(input, "AutoGenerated")
}

func ToPackageName(input string) string {
	words := splitWords(input)
	if len(words) == 0 {
		return ""
	}

	var builder strings.Builder
	for _, word := range words {
		builder.WriteString(strings.ToLower(word))
	}

	name := builder.String()
	if name == "" {
		return ""
	}

	first, _ := utf8.DecodeRuneInString(name)
	if unicode.IsDigit(first) {
		return "pkg" + name
	}

	return name
}

func UniqueName(base string, used map[string]int) string {
	if base == "" {
		base = "Generated"
	}

	count := used[base]
	used[base] = count + 1
	if count == 0 {
		return base
	}

	return base + strconv.Itoa(count+1)
}

func Singularize(input string) string {
	words := splitWords(input)
	if len(words) == 0 {
		return input
	}

	last := words[len(words)-1]
	lower := strings.ToLower(last)

	switch {
	case strings.HasSuffix(lower, "ies") && len(last) > 3:
		words[len(words)-1] = last[:len(last)-3] + "y"
	case hasPluralES(lower):
		words[len(words)-1] = last[:len(last)-2]
	case strings.HasSuffix(lower, "s") &&
		!strings.HasSuffix(lower, "ss") &&
		!strings.HasSuffix(lower, "us") &&
		!strings.HasSuffix(lower, "is") &&
		len(last) > 1:
		words[len(words)-1] = last[:len(last)-1]
	}

	return strings.Join(words, " ")
}

func toExportedName(input, fallback string) string {
	words := splitWords(input)
	if len(words) == 0 {
		words = []string{fallback}
	}

	var builder strings.Builder
	for _, word := range words {
		builder.WriteString(formatWord(word))
	}

	name := builder.String()
	if name == "" {
		name = fallback
	}

	first, _ := utf8.DecodeRuneInString(name)
	if unicode.IsDigit(first) {
		name = "X" + name
	}

	return name
}

func formatWord(word string) string {
	if word == "" {
		return ""
	}

	if isDigitsOnly(word) {
		return word
	}

	lower := strings.ToLower(word)
	if initialism, ok := commonInitialisms[lower]; ok {
		return initialism
	}

	runes := []rune(lower)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func isDigitsOnly(word string) bool {
	for _, r := range word {
		if !unicode.IsDigit(r) {
			return false
		}
	}

	return word != ""
}

func hasPluralES(word string) bool {
	suffixes := []string{"ses", "xes", "zes", "ches", "shes"}
	for _, suffix := range suffixes {
		if strings.HasSuffix(word, suffix) {
			return true
		}
	}

	return false
}

func splitWords(input string) []string {
	runes := []rune(input)
	if len(runes) == 0 {
		return nil
	}

	var words []string
	start := -1

	flush := func(end int) {
		if start >= 0 && end > start {
			words = append(words, string(runes[start:end]))
		}
		start = -1
	}

	for index, current := range runes {
		if !unicode.IsLetter(current) && !unicode.IsDigit(current) {
			flush(index)
			continue
		}

		if start == -1 {
			start = index
			continue
		}

		previous := runes[index-1]
		var next rune
		if index+1 < len(runes) {
			next = runes[index+1]
		}

		if shouldSplit(previous, current, next) {
			flush(index)
			start = index
		}
	}

	flush(len(runes))
	return words
}

func shouldSplit(previous, current, next rune) bool {
	if unicode.IsDigit(previous) != unicode.IsDigit(current) {
		return true
	}

	if unicode.IsLower(previous) && unicode.IsUpper(current) {
		return true
	}

	if unicode.IsUpper(previous) && unicode.IsUpper(current) && next != 0 && unicode.IsLower(next) {
		return true
	}

	return false
}
