package generator

import (
	"fmt"
	"go/format"
	"strings"

	"structify-go/internal/naming"
	schematypes "structify-go/internal/types"
)

type Options struct {
	PackageName string
}

func Generate(root *schematypes.StructDef, options Options) ([]byte, error) {
	packageName := naming.ToPackageName(options.PackageName)
	if packageName == "" {
		return nil, fmt.Errorf("invalid package name %q", options.PackageName)
	}

	definitions := collectDefinitions(root)

	var builder strings.Builder
	builder.WriteString("// Code generated by structify-go; DO NOT EDIT.\n\n")
	builder.WriteString("package ")
	builder.WriteString(packageName)
	builder.WriteString("\n\n")

	for index, definition := range definitions {
		writeStruct(&builder, definition)
		if index < len(definitions)-1 {
			builder.WriteString("\n")
		}
	}

	source, err := format.Source([]byte(builder.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w", err)
	}

	return source, nil
}

func collectDefinitions(root *schematypes.StructDef) []*schematypes.StructDef {
	seen := make(map[string]bool)
	definitions := make([]*schematypes.StructDef, 0)

	var visitType func(valueType *schematypes.ValueType)
	var visitStruct func(definition *schematypes.StructDef)

	visitType = func(valueType *schematypes.ValueType) {
		if valueType == nil {
			return
		}

		switch valueType.Kind {
		case schematypes.StructKind:
			visitStruct(valueType.StructDef)
		case schematypes.SliceKind:
			visitType(valueType.Element)
		}
	}

	visitStruct = func(definition *schematypes.StructDef) {
		if definition == nil || seen[definition.Signature] {
			return
		}

		seen[definition.Signature] = true
		definitions = append(definitions, definition)

		for _, field := range definition.Fields {
			visitType(field.Type)
		}
	}

	visitStruct(root)
	return definitions
}

func writeStruct(builder *strings.Builder, definition *schematypes.StructDef) {
	fmt.Fprintf(builder, "type %s struct {\n", definition.Name)
	for _, field := range definition.Fields {
		fmt.Fprintf(
			builder,
			"\t%s %s `json:\"%s\"`\n",
			field.Name,
			goType(field.Type),
			field.JSONName,
		)
	}
	builder.WriteString("}\n")
}

func goType(valueType *schematypes.ValueType) string {
	switch valueType.Kind {
	case schematypes.StringKind:
		return "string"
	case schematypes.BoolKind:
		return "bool"
	case schematypes.IntKind:
		return "int"
	case schematypes.Float64Kind:
		return "float64"
	case schematypes.InterfaceKind:
		return "interface{}"
	case schematypes.StructKind:
		return valueType.StructDef.Name
	case schematypes.SliceKind:
		return "[]" + goType(valueType.Element)
	default:
		return "interface{}"
	}
}
